app:
  jwt:
    access:
      secret: 423F4528482B4D6250655368566D597133743677397A24432646294A404E635266546A576E5A7234753778214125442A472D4B6150645367566B587032733576
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
            allowedHeaders: "Content-Type, Authorization"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products/**
          filters:
            - AuthenticationFilter
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/security/**
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/orders/**,/details/**
          filters:
            - AuthenticationFilter
        - id: payments-service
          uri: lb://payments-service
          predicates:
            - Path=/payments/**
          filters:
            - AuthenticationFilter
        - id: clients-service
          uri: lb://clients-service
          predicates:
            - Path=/clients/**
          filters:
            - AuthenticationFilter
        - id: eureka-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka-service/web
          filters:
            - SetPath=/
        - id: eureka-service-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            - trace
            - route:
                RouteDefinitionLocator: info
